### ISSUE TITLE
How can get only the headers?

### ISSUE THREAD

**Issue by argordmel** [ffalt/xlsx-extract#12]
Hi!

How can get only the headers. I've many file with 200K records but only need the headers name.

Thanks!

**Comment by ffalt** [comment]
Hi, headers are just rows, so xlsx-extract doesn't know e.g. how many rows are considered to be header. At the moment you can only get all rows, while counting and keeping the header rows. Unfortunatly there is no abort or only-get-number-of-rows functionalty, so you just have to ignore the others rows, iterating through the whole file.
