### ISSUE TITLE
Question: Ignore phonetic info

### ISSUE THREAD

**Issue by yuyuxing-wu** [ffalt/xlsx-extract#205]
Hi, 
I'm looking for a excel-streamreader and found this is very nice.
But I also found the phonetic information is included in the output.
Is anyway to ignore it?

**Comment by ffalt** [comment]
Hi! I'm not familiar with build-in phonetic information. Please provide a sample file for me to investigate.

**Comment by yuyuxing-wu** [comment]
[phonetic-sample.xlsx](https://github.com/ffalt/xlsx-extract/files/3894682/phonetic-sample.xlsx)
You can see a word "日本" which means "Japan" in A1 in "Sheet1".
And the phonetic infomation which by using the function "PHONETIC" in B1 in the same sheet.
When I try to get the text from "Sheet2" which has the same cell as A1 in "Sheet1", it will show "日本 二ホン".
The "PHONETIC" function may be available on Windows only while the phonetic info is available on any OS.

**Comment by ffalt** [comment]
It was a bug: the phonetic infomation should have been ignored by default, instead it was merged into the cell string.
I fix it it version [0.1.3](https://github.com/ffalt/xlsx-extract/blob/master/CHANGELOG.md#013-20191127) and released the new version to npm.

Thank you for reporting and the sample file!

**Comment by yuyuxing-wu** [comment]
Thank you for your quick response!
The issue was resolved!
