### ISSUE TITLE
Support for STORE zip compression

### ISSUE THREAD

**Issue by mikuso** [ffalt/xlsx-extract#4]
I have a use-case for parsing xlsx documents which are zipped with STORE compression (i.e. uncompressed).

[node-unzip](https://github.com/EvanOxfeld/node-unzip) does not support this, but [node-unzip-2](https://github.com/glebdmitriew/node-unzip-2) does.

node-unzip-2 is a fork of the former, and it's hot-swappable.

**Comment by mikuso** [comment]
pr #5

**Comment by ffalt** [comment]
merged & published to npm. thx!
